# Generated by Django 4.1.3 on 2022-12-22 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_order_email_orderitem_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdeliveryinfo',
            old_name='county',
            new_name='country',
        ),
    ]
