# Generated by Django 4.1.3 on 2022-12-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_rename_county_userdeliveryinfo_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='catagory',
            field=models.CharField(default='Ring', max_length=255),
        ),
    ]
